GET http://localhost:3000/api/eventos

###
POST http://localhost:3000/api/eventos
Content-Type: application/json

{
    "titulo": "Concierto de RUSSIAN CIRCLES",
    "fecha": "2023/04/02",
    "descripcion": "Después de haber tenido que cancelar el evento por culpa de la pandemia, tras dos años, este grupo de post-metal procedente de Chicago ha anunciado su puesta en escena en la sala Custom de Sevilla. No pierdas la oportunidad de conocerlos.",
    "imagen": "https://www.binaural.es/wp-content/uploads/2019/10/russian.jpg",
    "lugar": "Sala Custom, Sevilla"
}

### 
GET http://localhost:3000/api/usuarios 

###
POST http://localhost:3000/api/usuarios/registro
Content-Type: application/json

{
    "username": "eldeperezaa",
    "email": "eldeperezaa@gmail.com",
    "password": "12341234"
}

###
DELETE http://localhost:3000/api/eventos/1

###
PUT http://localhost:3000/api/eventos/4

###
GET http://localhost:3000/api/eventos/6